In [1]:
#task1
import numpy as np

a = np.empty((3, 3))
print(a)

[[2.78931765e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [2]:
#task1
import numpy as np

a = np.ones((1, 2))
print(a)

[[1. 1.]]


In [3]:
#task1
import numpy as np

a = np.full((3, 3), 5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [4]:
#task1
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5 , 6]])
array = np.zeros_like(a)
print(array)

[[0 0 0]
 [0 0 0]]


In [ ]:
#task1
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5 , 6]])
array = np.ones_like(a)
print(array)

[[1 1 1]
 [1 1 1]]


In [ ]:
#task1
import numpy as np
new_list = [1,2,3,4]
array=np.array(new_list)
print(array)

[1 2 3 4]


In [7]:
#task2
import numpy as np
array = np.arange(10, 30)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [6]:
#task2
import numpy as np
array = np.arange(0,9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#task2
import numpy as np
array = np.eye(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
#task2
import numpy as np
a = np.random.random(20)
mean_value = a.mean()
print("Array:", a)
print("Mean:", mean_value)

Array: [0.64184108 0.06463886 0.27418665 0.11735252 0.49936794 0.11823411
 0.68099021 0.17122612 0.59172082 0.94523103 0.5563256  0.48805052
 0.59618487 0.87386546 0.58472785 0.54306566 0.73769565 0.27272629
 0.18240213 0.21258998]
Mean: 0.4576211658944839


In [10]:
#task2
import numpy as np
a = np.random.random((5, 10))
min_value = a.min()
max_value = a.max()
print("Array: ", a)
print("Minimum value: ", min_value)
print("Maximum value: ", max_value)

Array:  [[0.95319824 0.64523307 0.95996566 0.49182904 0.51246953 0.83004407
  0.22190901 0.83378647 0.92232578 0.16499679]
 [0.52085458 0.26618742 0.8868844  0.52374037 0.59628659 0.55600446
  0.31606751 0.04676239 0.19226011 0.35004861]
 [0.52870099 0.90081151 0.07146589 0.38380477 0.69745354 0.67818443
  0.76743332 0.66344475 0.48030585 0.37197349]
 [0.78510605 0.32910259 0.59458835 0.73629647 0.04518931 0.79828559
  0.66786124 0.96477687 0.36331732 0.49119203]
 [0.62264762 0.98881011 0.72630071 0.69788447 0.57327742 0.13619245
  0.16299136 0.19434595 0.9080537  0.4778496 ]]
Minimum value:  0.04518930915190145
Maximum value:  0.9888101118097073


In [11]:
#task2
import numpy as np
a = np.zeros(10)
a[6] = 1
print(a)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


In [12]:
#task2
import numpy as np
arr = [1,2,3,0,4,6]
rev_array=arr[::-1]
print(rev_array)

[6, 4, 0, 3, 2, 1]


In [13]:
#task2
import numpy as np
arr = np.ones((2, 4))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#task2
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [15]:
from typing_extensions import MutableMapping
#task3
import numpy as np
x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
#1
add = x + y
print(add)
#2
sub= x - y
print(sub)
#3
multi = x * 7
print(multi)
#4
square = y ** 2
print(square)
#5
dot_1 = np.dot(v, w)
print(dot_1)
dot_2 = np.dot(x, v)
print(dot_2)
dot_3 = np.dot(x, y)
print(dot_3)
#6
concat_xy_rows = np.concatenate((x, y))
print(concat_xy_rows)
concat_vw_cols = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)))
print(concat_vw_cols)
#7
# The original error was due to concatenating a 2D array `x` (shape (2,2)) with a 1D array `v` (shape (2,)).
# To fix this, `v` needs to be reshaped to a 2D array (e.g., (1,2)) to be compatible for concatenation along axis 0.
concat_xv=np.concatenate((x, v.reshape(1, -1)), axis=0)
print(concat_xv)
#NumPy cannot concatenate a 2D array with a 1D array unless dimensions match.
#To concatenate successfully, v must be reshaped.

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 7 14]
 [21 35]]
[[25 36]
 [49 64]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9]
 [10]
 [11]
 [12]]
[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [17]:
#task4
import numpy as np
A = np.array([[1, 2],
              [7, 8]])
B = np.array([[1, 3],
              [2, 1]])
#1
A_inv = np.linalg.inv(A)
I=A@A_inv
print(I)
#2
AB = A @ B
BA = B @ A
print("AB ", AB)
print("BA", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))
#3
left = (A @ B).T
right = B.T @ A.T
print("Are they equal?", np.array_equal(left, right))
#Inverse method
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  2, -1]])

B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = A_inv @ B
print("Result", X)
#

[[1. 0.]
 [0. 1.]]
AB  [[ 5  5]
 [23 29]]
BA [[22 26]
 [ 9 12]]
Are AB and BA equal? False
Are they equal? True
Result [ 1.77272727  0.86363636 -1.95454545]
